include:
  - board: xiao_ble
    shield: totem_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: totem_central_left

  - board: xiao_ble
    shield: totem_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: totem_peripheral_right

  - board: xiao_ble
    shield: settings_reset
